name: Data request
description: Request WCGOP discard rates, totals, and biological samples.
title: "Data request for species [replace with your species]"
labels: ["type: request"]
assignees:
  - chantelwetzel-noaa
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out the WCGOP request form.
  - type: textarea
    id: species
    attributes:
      label: Identify the common name(s) 
  - type: dropdown
    id: data
    attributes:
      label: Type of data needed
      multiple: true
      options:
        - discard totals/rates
        - biological data
        - discard totals/rates and biological data
  - type: textarea
    id: info
    attributes:
      label: Gear grouping
      description: Please provide information on how you would like the data grouped by gear type. The gear groups are bottom trawl, fixed gear, hook and line, midwater trawl, pot, and shrimp trawl. The fixed gear grouping includes a range of gears from the nearshore across the coast. Not all gear types need to be included. For example, one could request data in two groupings of bottom and midwater trawl combined and hook and line, pot, and fixed gears combined. 
  - type: checkboxes
    id: clearance
    attributes:
      label: Do you you have clearance to access these data with a valid 2023 NDA form with WCGOP?
      description: By submitting this issue you agree that you have access to confidential data from WCGOP and will not share these data with those that do not have the same clearance.
      options:
        - label: I agree that I have clearance
          required: true
